# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('renting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='listed_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Emily', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
