# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renting_app', '0002_auto_20161206_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='renting_app.Category'),
        ),
    ]
